### ISSUE TITLE
Playstore alternative

### ISSUE THREAD

**Issue by IzzySoft** [lz1asl/CaveSurvey#124]
Would you mind attaching an `.apk` to the latest release (and future ones), and/or having your app published on F-Droid? That way it could also be used by folks without Playstore access.

**Comment by lz1asl** [comment]
Hello,
on the bottom of the front page there are links to Google Play and to the latest .apk (Jenkins CI provided by CloudBees). Let me know if you can't download it from there.
Best Regards

**Comment by IzzySoft** [comment]
Thanks a lot! Will try that as soon as I'm back home again.

For the second part of my question: Would you be OK with me filing an RFP (Request For Packaging) with F-Droid to take your app in? By a quick look at the gradle file I'd say it should fit their conditions.

**Comment by lz1asl** [comment]
I don't plan to support more app-stores. CaveSurvey is free to (re)use as it is.
