### ISSUE TITLE
Link to latest beta APK broken

### ISSUE THREAD

**Issue by IzzySoft** [lz1asl/CaveSurvey#132]
The link given in the README no longer works. Resulting page (!) says "account disabled". Will it come back – or would you maybe consider attaching the APKs to their corresponding `releases/` here at Github?

**Comment by lz1asl** [comment]
Yes, the build at CloudBees is broken. I will try to fix it in the next days.
What do you think is the best place for apk files e.g. people without Google Play or beta builds? Will the repo not grow a lot with binaries?

**Comment by IzzySoft** [comment]
I'd not place them *inside* the repo (i.e. `git add … commit`) – but next to it: Did you know you can attach them to their corresponding release (in [`releases/`](https://github.com/lz1asl/CaveSurvey/releases)? If not, steps are described in Github's documentation under [Creating Releases](https://help.github.com/articles/creating-releases/). You've got the code here anyway, so that'd be the best place for "material" you want to provide for your users, like you did with your wiki already. Wouldn't you agree? :wink:

**Comment by lz1asl** [comment]
I agree. Next releases will include the apk files also. Thank you @IzzySoft

**Comment by IzzySoft** [comment]
Thanks a lot! Please let me know when they are there.

**Comment by lz1asl** [comment]
Hey,

you can find the latest release here https://github.com/lz1asl/CaveSurvey/releases/edit/Release_v1.34

All the Best

**Comment by IzzySoft** [comment]
Thanks, that works now :+1:

**Comment by IzzySoft** [comment]
Uh, is there no APK for v1.37 – or did you just forget to attach it?

**Comment by lz1asl** [comment]
Sorry, added.

**Comment by IzzySoft** [comment]
Thanks! The updater fetched it :smiley:
