### ISSUE TITLE
Freez app on settings screen

### ISSUE THREAD

**Issue by seg-on** [lz1asl/CaveSurvey#140]
When I open Settings the app will freeze and I must kill the application. 
My device is Xiaomi Redmi Note 3 Pro.

**Comment by seg-on** [comment]
It's doesn't generate error because app don't crash. Only doesn't response.
When I click back nothing will happen.
On another device (Xiaomi redmi Note 5) it is working.

**Comment by lz1asl** [comment]
The only dangerous operation there is the error reporter that should either work (older devices) or be disabled. Adding extra check and leaving the issue open, please let me know if it still crashes with the next v39?

**Comment by seg-on** [comment]
Thanks I'll waiting for the new version and try it.

**Comment by lz1asl** [comment]
Hello, could you give it a try with the updated version? Is the issue still there?

**Comment by seg-on** [comment]
Hi, I updated app but the issue still persist :/

**Comment by lz1asl** [comment]
Ok, I have no clue what is causing this, will try to reproduce it at my side.

**Comment by lz1asl** [comment]
Could you make a backup of your surveys and try the Settings screen with this build? On your device the error reporter should still work and I have it turned on for the settings screen for you. With a stack trace the mistery should be easilly solved :)

[CaveSurvey-defaultFlavor-release.apk.zip](https://github.com/lz1asl/CaveSurvey/files/2811672/CaveSurvey-defaultFlavor-release.apk.zip)

**Comment by seg-on** [comment]
I'm not exactly understand what you mean, but I installed the CaveSurvey-defaultFlavor-release.apk.zip and it is still freezing. No error was generate. But now when i switch app or go to home and back, the app is in the home screen (list of projects) and I can control it.

**Comment by lz1asl** [comment]
It is strange that no message come to you. Could you try also this one? A message with the cause should show up.
[CaveSurvey-defaultFlavor-release.apk.zip](https://github.com/lz1asl/CaveSurvey/files/2812775/CaveSurvey-defaultFlavor-release.apk.zip)

**Comment by seg-on** [comment]
Still the same :/
But as I write. Application does not crash, only it does not react on touch or button back. It's looks like that still working.
No error. No meeage.

**Comment by lz1asl** [comment]
Pretty strange. Your device should be with 5.1.1 - I tried with the closest emulator I was able to find but can't reproduce it yet. Is there any change that you get the logs with adb so we get idea what is happening at your side?

**Comment by seg-on** [comment]
I can try it. But now I thinking that it is not so big issue to waste so many time :)

**Comment by lz1asl** [comment]
OK, let me know if you find time and get any logs.

**Comment by seg-on** [comment]
Say me where I found logs and I will test and send it to you.

**Comment by lz1asl** [comment]
In your case you will need to install android SDK, plug the cable and use one of the command line [tools](https://developer.android.com/studio/command-line/logcat). I should re-implement the reporting functionality for newer devices #138

**Comment by seg-on** [comment]
OK I'm prepared.

**Comment by lz1asl** [comment]
I think I have reproduced it locally. It should be fixed in the next release.
