### ISSUE TITLE
Can't acces exported files

### ISSUE THREAD

**Issue by seg-on** [lz1asl/CaveSurvey#141]
I can't access path where was exported file/files from project. I can't find the path. It is possibility that it is hidden.
And on another device fail export due access the directory.

**Comment by lz1asl** [comment]
Sorry about that, will be fixed in the next release

**Comment by seg-on** [comment]
Thanks! :)

**Comment by lz1asl** [comment]
Hey!
I have pushed updated version that tries to use the external storage so you can access the files with file manager as before. If external storage is not available you will still be able to use the app but should be warned about this.
Could you please give it a test and come back with comments?
All the best!

**Comment by seg-on** [comment]
Hi, yes this is working for me and another friend. Thanks! :)

**Comment by lz1asl** [comment]
There are still some issues with the initial screen but I hope you can now use the data. Sorry again.
