### ISSUE TITLE
Can't import xls

### ISSUE THREAD

**Issue by seg-on** [lz1asl/CaveSurvey#146]
I'm exporting project to xls and try to import on another device but id doesn't work.
Create new project without importing data.

**Comment by seg-on** [comment]
[┼átefan_prekop_20190207_1.xls.zip](https://github.com/lz1asl/CaveSurvey/files/2842119/atefan_prekop_20190207_1.xls.zip)

**Comment by lz1asl** [comment]
Hey, the issue should be fixed with the next release. I have further improved the error message so you should get a clue what's wrong next time.
Please give it a try and let me know if it is fixed.

**Comment by seg-on** [comment]
Hi,
now I can import the original exported file ┼átefan_prekop_20190207_1.xls
but when I try import edited file Stefan_prekop_20190207_1.xls it give error IllegalStateException : Cannot get a STRING value from a NUMBER cell. Even when I formať whole sheet as a TEXT.

![screenshot_2019-02-09-22-19-05-426_com astoev cave survey](https://user-images.githubusercontent.com/19683952/52526679-95c99280-2cbc-11e9-876a-64e1e93d91c0.png)

[┼átefan_prekop_20190207_1.xls.zip](https://github.com/lz1asl/CaveSurvey/files/2848301/atefan_prekop_20190207_1.xls.zip)

[Stefan_prekop_20190207_1.xls.zip](https://github.com/lz1asl/CaveSurvey/files/2848302/Stefan_prekop_20190207_1.xls.zip)

**Comment by lz1asl** [comment]
Excel has its own issues and formatting it properly is sometimes tricky. Please give a test to this build, if OK I will include it in the next release :
[CaveSurvey-defaultFlavor-release.apk.zip](https://github.com/lz1asl/CaveSurvey/files/2849315/CaveSurvey-defaultFlavor-release.apk.zip)

**Comment by seg-on** [comment]
Hmm. I installed the update, but now it looks like before last release and can't import an Excel (include the exported XLS without editing)

**Comment by lz1asl** [comment]
Hey, it could be something with the build I sent to you. I have published the fix that works at my side with your file, could you have a look?

**Comment by seg-on** [comment]
On google play I see release version from 9.2.2018. It is possible somewhere download newer release?

**Comment by lz1asl** [comment]
Give me some more time, I want to make sure next version will import your file.

**Comment by seg-on** [comment]
Oh Yes. I was understand that it is released :)

**Comment by lz1asl** [comment]
Actually you are right, I have not pushed the latest changes, will release again.
