### ISSUE TITLE
Wiki advice out of date

### ISSUE THREAD

**Issue by Hornbydd** [lz1asl/CaveSurvey#161]
Under the About section in the wiki user guide you state that CaveSurvey can be used by "Android 2.1+ device", but if you go on the play store it clearly states than you need a minimum of version 4 as shown below.

![image](https://user-images.githubusercontent.com/22773948/91434317-8db05400-e85c-11ea-8da6-af0520e8adc0.png)

When I forked a copy of your project it appears the wiki does not copy over so I cannot edit this, so I bring it to your attention.

I have an old HTC phone which is 2.2 Android and it refused to install it.

**Comment by lz1asl** [comment]
Thank you for spoting this. I will update the wiki.
The minimal version was recently increased, see https://github.com/lz1asl/CaveSurvey/releases/tag/Release_v1.44. If you want to use your Android 2.2 device simply download and install slightly older version attached to https://github.com/lz1asl/CaveSurvey/releases/tag/Release_v1.43 or previous releases.
