### ISSUE TITLE
Exporting data not working

### ISSUE THREAD

**Issue by carverhaines** [lz1asl/CaveSurvey#162]
When going to the data section of the app, it will correctly export the excel spreadsheet using the up/down arrows icon, however when going into the penguin icon (openspeleo) it opens the openspeleo site with the default cave map ("Grotta Fada") and not my own cave. So I cannot export to .th or any other file type other than .xls and .tro files at the moment.

Let me know if you know what is going on, maybe I can look into it. I love this app and project, and will try and contribute as time allows!

**Comment by lz1asl** [comment]
This should be something new. Could you please share the .xls and _openstopo.json export files so I can try to reproduce your issue? Meanwhile you can still use the .tro in Visual Topo (on a proper computer) for Therion export.

**Comment by carverhaines** [comment]
[Archive.zip](https://github.com/lz1asl/CaveSurvey/files/5329605/Archive.zip)
I've attached the zip file of all of the various exports.
I've also attached a screenshot of what clicking the pengin icon does, it simply takes me to http://www.openspeleo.org/opstopo/ which loads the default map. Is it supposed to be importing my map data? It does show the correct name of my cave in the top left.
![Screenshot_20201005-141414](https://user-images.githubusercontent.com/5835343/95122592-5c0d9100-0716-11eb-94a8-4bd611cac9a4.jpg)

**Comment by lz1asl** [comment]
Thank you for reporting this! It seems the generated OpensTopo json file is no more valid. This explains the default values and should be regression from the refactoring related to Visual Topo implementation. Will prepare fix for the next version.

**Comment by lz1asl** [comment]
Fixed in the latest 1.50 release

**Comment by carverhaines** [comment]
Thank you!
