### ISSUE TITLE
Use with the CEM ILDM-30?

### ISSUE THREAD

**Issue by carverhaines** [lz1asl/CaveSurvey#163]
I have the CEM ILDM-30 bluetooth distance only laser meter.
Any chance of being able to connect to that to use the length measurements?

It's also a good entry/budget device, so people can begin surveying with their phone's built in sensors plus a $32 USD distance meter.

**Comment by lz1asl** [comment]
The new unit looks good.
Let's try using the same protocol (Their [Android app](https://play.google.com/store/apps/details?id=com.cem.client.Meterbox.iLDM&hl=en) is last updated 3 years ago ;) ) 
Let me know what is the Bluetooth name of the device ("iLDM-30"?) and I will send you test version.
Related to #18

**Comment by carverhaines** [comment]
Yes, "iLDM-30"

**Comment by carverhaines** [comment]
I downloaded their android app to test the device, it was horrendous.

**Comment by lz1asl** [comment]
Ok, please try with the provided build. Follow the instructions at https://github.com/lz1asl/CaveSurvey/wiki/iLDM-150 and let me know of the result :) Note, that due #18 you might need to currently press twice the button to receive measurement.
[CaveSurvey-defaultFlavor-debug.zip](https://github.com/lz1asl/CaveSurvey/files/5386202/CaveSurvey-defaultFlavor-debug.zip)

**Comment by carverhaines** [comment]
Not sure how the pairing is supposed to work... When I use their app (ildm Meterbox), and refresh the bluetooth, it shows up, and starts reading measurements. The bluetooth device never pairs in the android bluetooth settings menu.
When I open the CaveSurvey app and tap a measurement, and push measure button on device nothing happens. When I go to the bluetooth menu in CaveSurvey no device shows, so I tapped the "+" button, scanned for the device, saw it, it said connecting, then said "can't communicate with device" (see images 1, 2, 3 below)

![Screenshot_20201015-185229](https://user-images.githubusercontent.com/5835343/96199106-4d945600-0f1c-11eb-85c6-249cc4ebe1a7.jpg)  ![Screenshot_20201015-191336](https://user-images.githubusercontent.com/5835343/96199314-d0b5ac00-0f1c-11eb-9f86-84dc8c4c1193.jpg)  ![Screenshot_20201015-191914](https://user-images.githubusercontent.com/5835343/96199327-d8755080-0f1c-11eb-88b4-a23f42f6af2e.jpg)

When trying to add the device directly through android's bluetooth menu, it asks for a passcode, which the manual for the iLDM-30 says is "0000" I enter that and it just goes back into search mode showing the iLDM as ready for pairing again, with no errors. It never directly pairs. (see image 4 below)

![Screenshot_20201015-185306](https://user-images.githubusercontent.com/5835343/96199444-1bcfbf00-0f1d-11eb-9e00-91412567b53a.jpg)


Is this expected behaviour? Is it the same for the iLDM 150?

**Comment by lz1asl** [comment]
OK, I should try to rework the [general usage](https://github.com/lz1asl/CaveSurvey/wiki/Measurement-Devices#general-usage) description.
For COMM based communication (older Bluetooth devices and the current iLDM implementation we have) you should first pair with Android (as you did with the 0000 pin). Then on the devices screen (your first screenshot) the combo box should be filled with a list of all paired and compatible ones. Once you select a device CaveSurvey tries to connect (the yellow notification on success) and use. Next step is to create a survey project with distance over Bluetooth (for iLDM inclination works as well but you need to switch the mode to measure inclination) and to select a distance aware cell. Measure with the device (in your case probably twice) the value should be populated in the cell.
Can you try to go one more time to the devices screen and check if the combo is still empty after the pairing?

**Comment by carverhaines** [comment]
So I can pair with android, putting in '0000', but it never really pairs or shows up in the list of known devices, it immediately shows back up in the list of devices ready to pair, and therefore never shows up in the "Devices" screen of CaveSurvey. I was wondering if that was normal behaviour. Of note, I can pair it w/ my Windows laptop, and it does seem to pair. The android app by the developer does show it in the list of devices, and I can get measurement readings through their app, but the device is still never really paired with the phone even when using their app (android bluetooth menu does not show it, and it is not available for pairing).
Is that as expected?

**Comment by lz1asl** [comment]
I don't know why it is not pairing. To use this protocol with CaveSurvey the pairing should succeed. There is just one very generic line in the manual about the Bluetooth ...
Let us try something else, can you try to use other Android phone or this app and see what will happen https://play.google.com/store/apps/details?id=de.dirkfarin.imagemeter&hl=en?

**Comment by carverhaines** [comment]
Same thing on that other app, it needs it successfully paired first.
Using a different (older) phone gave some insight, this time instead of failing silently, it said "Incorrect PIN or passkey" even though the manual clearly states '0000'. I tried 1234 as well. 
Strangely, when I pair it with my Windows laptop it pairs correctly with code '0000' and shows up as an active device.
Strange...

**Comment by lz1asl** [comment]
It seems like it is either using LE protocol without pairing or there is some issue with the unit. In both cases I cannot help remotely. Where are you located, is there any chance to borrow your device?

**Comment by carverhaines** [comment]
I'm guessing the way it acts is using BLE, because it just seems to be listening to that MAC address, not ever pairing.
I live in the US, I'm guessing you're in Bulgaria? It would probably cost more to ship than the device is even worth. 
I'm thinking of just returning it in exchange for the iLDM 150 instead since we know that one would work.

**Comment by lz1asl** [comment]
OK, in this case I will postpone the support for this device.
And you can pick also one of the other cheap [devices](https://github.com/lz1asl/CaveSurvey/wiki/Measurement-Devices#devices) that are more compact like yours.
Good luck surveying!
