### ISSUE TITLE
Add Therion export format 

### ISSUE THREAD

**Issue by theSCRAG** [lz1asl/CaveSurvey#40]
Please add Therion export format in order to import data direct to Therion.

**Comment by lz1asl** [comment]
Hey,
see this issue - https://github.com/lz1asl/CaveSurvey/issues/34
We are preparing integration with OpensTopo (http://www.openspeleo.org/openspeleo/openstopo.en.html) wich have export to KML, DXF and also Therion. We are close, so stay tuned :)

**Comment by theSCRAG** [comment]
One question: openstopo is only ONLINE converting - is that right?

In this case it's not possible to finish the survey (=mapping) direct after the trip. If you stay somewhere in the wild.



<div>-------- Ursprüngliche Nachricht --------</div><div>Von: lz1asl <notifications@github.com> </div><div>Datum:16.01.2015  19:56  (GMT+01:00) </div><div>An: lz1asl/CaveSurvey <CaveSurvey@noreply.github.com> </div><div>Cc: theSCRAG <speleo@web.de> </div><div>Betreff: Re: [CaveSurvey] Add Therion export format  (#40) </div><div>
</div>Hey,
see this issue - #34
We are preparing integration with OpensTopo (http://www.openspeleo.org/openspeleo/openstopo.en.html) wich have export to KML, DXF and also Therion. We are close, so stay tuned :)

**Comment by lz1asl** [comment]
Thanks to the OpensTopo author Alessandro it is going to run offline - webview using embedded resources (if you have noticed the html and js resources in the project). So you should be able to use all features without going online.
If you want to help I can send you early builds when ready?

Best,
Aleksandar

**Comment by theSCRAG** [comment]
Hi Aleksandar,

I have seen the directory, but don't look in the source.
If offline export in Therion format is working with OpensTopo, then it's also well.
I would testing issue #34 

So this issue could close.

**Comment by lz1asl** [comment]
All interested in Therion format might have a look at the new release. Too old devices might not work correctly.
